### ISSUE TITLE
找不到rss.xml

### ISSUE THREAD

**Issue by geekmister** [surmon-china/nodepress#83]
```
[error] [nodepress] (node:10300) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/geekchief/Desktop/Work/Workspace/Geekkampong/gm/surmon.me/public/rss.xml'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at /Users/geekchief/Desktop/Work/Workspace/Geekkampong/gm/blog-api/dist/modules/syndication/syndication.service.js:198:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
```

yarn start后，报这个错误，rss.xml怎么编写？有没有样例，需要帮助，感谢感谢！

**Comment by surmon-china** [comment]
这个错误现在就不存在了，因为 Nodepress 应用[移除 RSS 相关业务](https://github.com/surmon-china/nodepress/blob/main/CHANGELOG.md#v360-2021-12-06)了。
